In [1]:
from collections import Counter
import pandas as pd

In [2]:
def prepare_data(data, y_col_name, test_size = 0.15):
    
    import datetime as dt
    # считаем индекс в датафрейме, после которого начинается тестовыый отрезок
    test_index = int(data.index[int((1-test_size)*len(data))])
    
    data = data.dropna()
    
    X_train = data.loc[:test_index-1].drop([y_col_name], axis=1)
    y_train = data.loc[:test_index-1][y_col_name]
    X_test = data.loc[test_index:].drop([y_col_name], axis=1)
    y_test = data.loc[test_index:][y_col_name]

    return X_train, X_test, y_train, y_test

In [3]:
def plot_data(header, y_train, y_test, prediction_train, prediction_test):
    from sklearn.metrics import mean_absolute_error, explained_variance_score, r2_score
    import matplotlib.pyplot as plt

    plt.figure(figsize=(15, 7))
    plt.plot(y_train, label="actual train")
    plt.plot(y_test, label="actual test")
    plt.plot(prediction_train, label = "prediction train")
    plt.plot(prediction_test, label="prediction test")
    plt.legend(loc="best")
    plt.title(header + "\n Metrics on test part: \n Mean absolute error {}".format(mean_absolute_error(prediction_test, y_test)) 
              + "\n Explained variance regression score {}".format(explained_variance_score(prediction_test, y_test))
              + "\n R2 score {}".format(r2_score(prediction_test, y_test)))
    plt.grid(True);

In [63]:
def plot_model(model, model_name, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    prediction_test = model.predict(X_test)
    prediction_test = list(map(round, prediction_test))
    prediction_test = list(map(int, prediction_test))
    
    prediction_train = model.predict(X_train)
    prediction_train = list(map(round, prediction_train))
    prediction_train = list(map(int, prediction_train))
    
    print(prediction_test)
    
    pred_test = pd.DataFrame(prediction_test, index = y_test.index)
    pred_train = pd.DataFrame(prediction_train, index = y_train.index)
    #print(pred_test)
    
    plot_data(model_name, y_train, y_test, pred_train, pred_test)

In [76]:
def get_pred_by_one_model(model, X_train, X_test, Y_train):
    model.fit(X_train, y_train)
    prediction_train = model.predict(X_train)
    prediction_train = list(map(round, prediction_train))
    prediction_train = list(map(int, prediction_train))
    return prediction_train

In [79]:
def get_pred_value_by_two_models(model1, model2, X_train, X_test, Y_train):
    p1 = getpred_by_one_model(model1, X_train, X_test, Y_train)
    p2 = getpred_by_one_model(model2, X_train, X_test, Y_train)
    return int(round((p1[0] + p2[0])/2))

In [ ]:
def get_part_of_sales(sales, shop_id, item_id):
    part = sales[(sales.ShopId == shop_id) & (sales.ItemId == item_id)]
    data = part[['DateBlockNum', 'ItemCntDay']]
    data.index = range(len(data))
    data = data.groupby('DateBlockNum').sum()
    data['DateBockNum'] = data.index
    return data

In [ ]:
def get_preds_between(sales, tests, ind_from, ind_to):
    predictions = pd.DataFrame(columns = ['ID', 'item_cnt_month'])
    for test_ind in range(ind_from, ind_to):
        part = get_part_of_sales(sales, tests.iloc[test_ind].ShopId, tests.iloc[test_ind].ItemId)
        if (len(part) > 0):
            X_train = part.drop([y_col_name], axis=1)
            y_train = data[y_col_name]
            X_test = X_train.iloc[0]
        else:
            predictions.loc[len(predictions)] = [test_ind, 0]

In [5]:
%matplotlib inline
sales_fname = 'sales_train_v2.csv'
sales_fname_data = 'sales_train_data.csv'
sales_column_names = ['Date', 'DateBlockNum', 'ShopId', 'ItemId', 'ItemPrice', 'ItemCntDay']
items_fname = 'items.csv'
items_column_names = ['ItemName', 'ItemId', 'ItemCategoryId']
shops_fname = 'shops.csv'
shops_column_names = ['ShopName', 'ShopId']
tests_fname = 'test.csv'
tests_column_names = ['Id', 'ShopId', 'ItemId']

In [6]:
sales = pd.read_csv(sales_fname_data, engine='c',
                  header = 0, names = sales_column_names)
items = pd.read_csv(items_fname, engine='c',
                  header = 0, names = items_column_names)
shops = pd.read_csv(shops_fname, engine='c',
                  header = 0, names = shops_column_names)
tests = pd.read_csv(tests_fname, engine='c',
                  header = 0, names = tests_column_names)

In [36]:
#2,8,10,13,
test_ind = 8
part_sales = sales[(sales.ShopId == tests.iloc[test_ind].ShopId) & (sales.ItemId == tests.iloc[test_ind].ItemId)]
item_info = items[items.ItemId == tests.iloc[test_ind].ItemId]
shop_info = shops[shops.ShopId == tests.iloc[test_ind].ShopId]

In [37]:
part_sales

         Date  DateBlockNum  ShopId  ItemId  ItemPrice  ItemCntDay
2150567   692            22       5    5319      299.0         5.0
2288611   706            23       5    5319      299.0         2.0
2288612   705            23       5    5319      299.0         2.0
2288613   704            23       5    5319      299.0         1.0
2288614   701            23       5    5319      299.0         5.0
2288615   699            23       5    5319      299.0         2.0
2288640   710            23       5    5319      299.0         2.0
2288642   711            23       5    5319      299.0         1.0
2288643   714            23       5    5319      299.0         1.0
2288665   728            23       5    5319      299.0         1.0
2288666   726            23       5    5319      299.0         1.0
2288667   725            23       5    5319      299.0         3.0
2288668   724            23       5    5319      299.0         1.0
2288669   723            23       5    5319      299.0         1.0
2288670   719            23       5    5319      299.0         1.0
2288671   718            23       5    5319      299.0         2.0
2288672   715            23       5    5319      299.0         1.0
2288673   712            23       5    5319      299.0         1.0
2335395   731            24       5    5319      299.0         1.0
2335396   733            24       5    5319      299.0         1.0
2335397   735            24       5    5319      299.0         1.0
2335398   736            24       5    5319      299.0         1.0
2335399   737            24       5    5319      299.0         2.0
2335400   738            24       5    5319      299.0         1.0
2335401   740            24       5    5319      299.0         1.0
2335420   730            24       5    5319      299.0         1.0
2457333   782            25       5    5319      299.0         1.0
2457340   769            25       5    5319      299.0         1.0
2528445   795            26       5    5319      299.0         1.0
2528446   803            26       5    5319      299.0         1.0
2528447   810            26       5    5319      299.0         1.0
2603087   840            27       5    5319      299.0         1.0
2603088   831            27       5    5319      299.0         1.0
2618932   851            28       5    5319      299.0         1.0
2618933   865            28       5    5319      299.0         1.0
2704055   908            29       5    5319      299.0         1.0
2704056   904            29       5    5319      299.0         1.0
2704072   893            29       5    5319      299.0         1.0
2704073   899            29       5    5319      299.0         1.0
2719240   933            30       5    5319      299.0         1.0
2719241   927            30       5    5319      299.0         1.0
2719242   914            30       5    5319      299.0         1.0
2811253   970            31       5    5319      299.0         1.0
2811919   958            31       5    5319      299.0         1.0
2861003   982            32       5    5319      299.0         1.0
2861004   997            32       5    5319      299.0         1.0
2861005  1000            32       5    5319      299.0         1.0

In [38]:
data = part_sales[['DateBlockNum', 'ItemCntDay']]
data.index = range(len(data))

In [88]:
data = data.groupby('DateBlockNum').sum()
data['DateBockNum'] = data.index

In [89]:
data

              ItemCntDay  DateBockNum
DateBlockNum
22                   5.0           22
23                  28.0           23
24                   9.0           24
25                   2.0           25
26                   3.0           26
27                   2.0           27
28                   2.0           28
29                   4.0           29
30                   3.0           30
31                   2.0           31
32                   3.0           32

In [90]:
X_train, X_test, y_train, y_test = prepare_data(data, 'ItemCntDay', test_size = 0.1)
#X_test

In [105]:
X_train.iloc[0] = 44

In [111]:
X_test = pd.DataFrame(columns = ['test'])
X_test.loc[len(X_test)] = [33]

In [108]:
%matplotlib inline
from sklearn.ensemble import BaggingRegressor

model = BaggingRegressor()
model.set_params(**{'n_estimators': 10, 'max_samples': 1.0, 
                     'max_features': 1.0, 'random_state': 42})
name = 'BaggingRegressor'
plot_model(model, name, X_train, X_test, y_train, y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[33].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
%matplotlib inline
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.set_params(**{'random_state':42})
name = 'RandomForestRegressor'
plot_model(model, name, X_train, X_test, y_train, y_test)

In [68]:
predictions = pd.DataFrame(columns = ['ID', 'item_cnt_month'])

In [74]:
predictions.loc[len(predictions)] = [0, 5]

In [75]:
predictions

  ID item_cnt_month
0  0              5
1  0              5
2  0              5